environment:
  GitHubAccessToken:
    secure: vpFm+bVGaeyr4e2n5Tr2Dbozp8/v/mgBplu1j7b1WIC5LhznyN81RycRe9qXMQ0Z

version: 1.0.2.{build}
build_script:
- ps: |
    # Check Version of PowerShell
    $PSVersionTable

    # Initialise
    . .\CICD\BuildHelpers.ps1
    $agent = New-BuildAgent

    # Build Actions
    $agent.SetBuildNumber()
    Write-Host "`r`nManifest version updated to: " $agent.VersionToString()

test_script:
- ps: |
    # Check Version of PowerShell
    $PSVersionTable

    # Initialise
    . .\CICD\BuildHelpers.ps1
    Install-Module -Name Pester -Force
    Import-Module Pester -MinimumVersion 5.0.0
    
    # Testing Actions
    $config = New-PesterCIConfiguration -IgnoreRemoteFilesystem -MSWordNotAvailable -IncludeCoverage -IncludeResults -IncludeDetail 
    $result = Invoke-Pester -Configuration $config
    $agent = New-BuildAgent
    $agent.SetAutomationCoverageBadge($result)
    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $config.TestResult.OutputPath.Value))

    # Status
    $env:TEST_FAIL_COUNT=$result.FailedCount

after_test:
- ps: |
    if ( $env:TEST_FAIL_COUNT -gt 0) { throw "$($env:TEST_FAIL_COUNT) tests failed, failing build." } else { Write-Host "All tests passed." }

on_finish:
- ps: |
    if ( $env:APPVEYOR_REPO_BRANCH -in @("develop", "release")) {
        Write-Host "Committing build number and automation coverage to branch" 
    } else { 
        Write-Host "Bypassing commit for feature and fix branches"

        git config --global credential.helper store
        Add-Content "$HOME\.git-credentials" "https://$($env:GitHubAccessToken):x-oauth-basic@github.com`n"
        git config --global user.email "build@appveyor.com"
        git config --global user.name "Appveyor"
        git checkout $env:APPVEYOR_REPO_BRANCH
        git add *.psd1
        git add *.md
        git commit -m "[skip ci] AppVeyor CI $($env:APPVEYOR_BUILD_VERSION)"
        git push --set-upstream origin $env:APPVEYOR_REPO_BRANCH
    } 

