environment:
  GitHubAccessToken:
    secure: vpFm+bVGaeyr4e2n5Tr2Dbozp8/v/mgBplu1j7b1WIC5LhznyN81RycRe9qXMQ0Z

version: 0.9.10.{build}
build_script:
- ps: >-
    $PSVersionTable

    . .\CICD\BuildHelpers.ps1

    $agent = New-BuildAgent

    $agent.SetBuildNumber()

    write-Host "Manifest version updated to: " ($agent.GetManifestVersion()[0])

- git config --global credential.helper store
- ps: Add-Content "$HOME\.git-credentials" "https://$($env:GitHubAccessToken):x-oauth-basic@github.com`n"
- git config --global user.email "build@appveyor.com"
- git config --global user.name "Appveyor"
- git checkout %APPVEYOR_REPO_BRANCH%
- git add *.psd1
- git commit -m "[skip ci] AppVeyor Build %APPVEYOR_BUILD_VERSION%"
- git push --set-upstream origin %APPVEYOR_REPO_BRANCH%

test_script:
- ps: >-
    $PSVersionTable

    . .\CICD\BuildHelpers.ps1

    Install-Module -Name Pester -Force

    Import-Module Pester -MinimumVersion 5.0.0

    $config = New-PesterCoverageConfiguration -IgnoreRemoteFilesystem -MSWordNotAvailable

    $result = Invoke-Pester -Configuration $config

    #$agent = New-BuildAgent

    #$agent.SetAutomationCoverage($result)

- git config --global credential.helper store
- ps: Add-Content "$HOME\.git-credentials" "https://$($env:GitHubAccessToken):x-oauth-basic@github.com`n"
- git config --global user.email "build@appveyor.com"
- git config --global user.name "Appveyor"
- git checkout %APPVEYOR_REPO_BRANCH%
- git add README.md
- git commit -m "[skip ci] AppVeyor Testing %APPVEYOR_BUILD_VERSION%"
- git push --set-upstream origin %APPVEYOR_REPO_BRANCH%

- ps: >-
    . .\CICD\BuildHelpers.ps1

    $config = New-PesterAppveyorReportConfiguration -IgnoreRemoteFilesystem -MSWordNotAvailable

    $result = Invoke-Pester -Configuration $config
    
    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $config.TestResult.OutputPath.Value))
    
    if ($result.FailedCount -gt 0) {

        throw "$($result.FailedCount) tests failed."
    
    }
