version: 0.9.{build}
build_script:
- ps: >-
    $PSVersionTable
    
    Install-Module -Name Pester -Force

    . .\Tests\Helpers\BuildHelpers.ps1

    Invoke-PesterCoverageTest -IgnoreRemoteFilesystem -MSWordNotAvailable