environment:
  GitHubAccessToken:
    secure: vpFm+bVGaeyr4e2n5Tr2Dbozp8/v/mgBplu1j7b1WIC5LhznyN81RycRe9qXMQ0Z

version: 0.9.10.{build}
build_script:
- ps: >-
    $PSVersionTable

    . .\CICD\BuildHelpers.ps1

    $agent = New-BuildAgent

    $agent.SetBuildNumber()

    write-Host "Manifest version updated to: " $agent.GetManifestVersion()

test_script:
- ps: >-
    $PSVersionTable

    . .\CICD\BuildHelpers.ps1

    Install-Module -Name Pester -Force

    Import-Module Pester -MinimumVersion 5.0.0

    # $config = New-PesterCoverageConfiguration -IgnoreRemoteFilesystem -MSWordNotAvailable

    $config = New-PesterDetailedTestConfiguration

    $result = Invoke-Pester -Configuration $config

    #$agent = New-BuildAgent

    #$agent.SetAutomationCoverage($result)



