version: 0.9.9.{build}
build_script:
- ps: >-
    $PSVersionTable
    
    Install-Module -Name Pester -Force

    Import-Module Pester -MinimumVersion 5.0.0

    . .\Tests\Helpers\BuildHelpers.ps1

    #$config = New-PesterCoverageConfiguration -IgnoreRemoteFilesystem -MSWordNotAvailable

    #$result = Invoke-Pester -Configuration $config

    write-Host "Build Number $($Env:APPVEYOR_BUILD_VERSION) $($Env:APPVEYOR_BUILD)"

test_script:
- ps: >-