#
# Module manifest for module 'PS.MediaCollectionManagement'
#
# Generated by: Luca Gnezda
#
# Generated on: 21/08/2021
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'PS.MediaCollectionManagement.psm1'
    
    # Version number of this module (Major.Minor.Fix.Build).
    ModuleVersion = '0.9.10.37'
    
    # ID used to uniquely identify this module
    GUID = 'a66d5170-23f2-40f4-8b8b-75f20dc4d471'
    
    # Author of this module
    Author = 'Luca Gnezda'
    
    # Company or vendor of this module
    CompanyName = 'Unknown'
    
    # Copyright statement for this module
    Copyright = '(c) 2021 Luca Gnezda. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'PowerShell module for modelling and managing media content on filesystem.'
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Content', 'Media', 'Filesystem', 'Model')
    
            # A URL to the license for this module.
            LicenseUri = 'https://github.com/LucaGnezda/PSMediaCollectionManagement/blob/main/LICENSE'
    
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/LucaGnezda/PSMediaCollectionManagement'
    
            # ReleaseNotes of this module
            ReleaseNotes = 'Refer to Github project'
    
        } # End of PSData hashtable
    
    } # End of PrivateData hashtable
    
}
 
